### ISSUE TITLE
crashed

### ISSUE THREAD

**Issue by 354651432** [arkane-systems/genie#10]
Unhandled exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.ComponentModel.Win32Exception: No such file or directory
   at Interop.Sys.ForkAndExecProcess(String filename, String[] argv, String[] envp, String cwd, Boolean redirectStdin, Boolean redirectStdout, Boolean redirectStderr, Boolean setUser, UInt32 userId, UInt32 groupId, Int32& lpChildPid, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean shouldThrow)
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start(String fileName, String arguments)
   at ArkaneSystems.WindowsSubsystemForLinux.Genie.Program.InitializeBottle(Boolean verbose)
   at ArkaneSystems.WindowsSubsystemForLinux.Genie.Program.InitializeHandler(Boolean verbose)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at System.CommandLine.Invocation.ModelBindingCommandHandler.InvokeAsync(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass2_0.<<InvokeAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Invocation.InvocationExtensions.<>c.<<UseParseErrorReporting>b__16_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Invocation.InvocationExtensions.<>c__DisplayClass8_0.<<UseTypoCorrections>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Invocation.InvocationExtensions.<>c.<<UseSuggestDirective>b__7_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Invocation.InvocationExtensions.<>c.<<UseDebugDirective>b__4_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Invocation.InvocationExtensions.<>c.<<UseParseDirective>b__6_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Invocation.InvocationExtensions.<>c.<<UseHelp>b__14_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass3_0.<<UseVersionOption>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Invocation.InvocationExtensions.<>c.<<RegisterWithDotnetSuggest>b__17_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Invocation.InvocationExtensions.<>c__DisplayClass5_0.<<UseExceptionHandler>b__0>d.MoveNext()

**Comment by 354651432** [comment]
## file mode is 
```-rwxrwxr-x  1 root root  20992 Jul  9 06:14 Linux.ProcessManager.dll*
-rwxrwxr-x  1 root root 149088 Jul  9 06:14 System.CommandLine.dll*
-rwxrwxr-x  1 root root 108544 Jul  9 06:14 Tmds.LibC.dll*
-rwsrwxr-x  1 root root 106912 Jul  9 06:14 genie*
-rwxrwxr-x  1 root root  13312 Jul  9 06:14 genie.dll*
-rw-rw----  1 root root    224 Jul  9 06:14 genie.runtimeconfig.json
```

**Comment by cerebrate** [comment]
Can you confirm that you have both daemonize and unshare installed? This is the exception you'd receive if one of them were to be missing.

**Comment by 354651432** [comment]
what is unshare? please

**Comment by cerebrate** [comment]
[Unshare(1)](https://linux.die.net/man/1/unshare) is a utility genie uses to create the namespaces for the bottle systemd runs in. It expects it to be found at /usr/bin/unshare.

Also present should be /bin/mount, /usr/sbin/daemonize, /lib/systemd/systemd, /usr/bin/nsenter, and /bin/login . Check that all those files are in place and executable; if one or more are missing - or if your distribution puts them in a different place than standard - that's your problem.

**Comment by 354651432** [comment]
is it ok ,thanks
