### ISSUE TITLE
当 hosts 文件配置错误时，genie 不能初始化

### ISSUE THREAD

**Issue by falseUtopia** [arkane-systems/genie#247]
**Windows version (build number):**
`Microsoft Windows [版本 10.0.19044.1586]`

**Linux distribution:**
`20.04.4 LTS (Focal Fossa)`

**Genie version:**
`genie 2.0`

**Describe the bug**

我的hosts 配置文件像这样时
![image](https://user-images.githubusercontent.com/19901195/158581262-89132bc3-4f64-4d17-8d3d-a992cf31b882.png)
执行 `genie -s`
![image](https://user-images.githubusercontent.com/19901195/158583770-1e0a2df2-c956-47b9-9def-1c9247f73829.png)

$ genie -s
genie: WARNING: systemd default target is default.target; targets other than multi-user.target may not work
genie: WARNING: if you wish to use a different target, this warning can be disabled in the config file
genie: WARNING: if you experience problems, please change the target to multi-user.target
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/lib/genie/genie/__main__.py", line 791, in <module>
  File "/usr/lib/genie/genie/__main__.py", line 775, in entrypoint
  File "/usr/lib/genie/genie/__main__.py", line 515, in do_initialize
  File "/usr/lib/genie/genie/__main__.py", line 221, in hostname_update
  File "/usr/lib/genie/genie/__main__.py", line 257, in modify_hosts_file_entries
  File "/usr/lib/genie/genie/python_hosts/hosts.py", line 157, in __init__
  File "/usr/lib/genie/genie/python_hosts/hosts.py", line 496, in populate_entries
  File "/usr/lib/genie/genie/python_hosts/hosts.py", line 54, in __init__
Exception: Address and Name(s) must be specified.
could not initialise bottle, exit code = 1

**Confirm that you are running inside the bottle:**
`no-bottle`

**To Reproduce**
例子：
1.  配置你的`hosts`文件 （我知道这并不是规范的`hosts`配置方式，我只希望genie的代码更有健壮性）

192.168.31.1 hostname1.com      
192.168.31.2                   
192.168.31.3 hostname3.com      

2.  在 `wsl` 的 `Ubuntu`内 安装 `genie`  
3.  执行 `genie -s`

**Expected behavior**
正常时控制台会提示等待 name.service 启动

**Additional context**
我看了代码，是在这个文件操作的

https://github.com/arkane-systems/genie/blob/master/binsrc/genie/__main__.py 的259行

`
...
 hosts.find_all_matching (name = old_name)
...
`
当我修改`hosts`文件使其变得正常时， 一切都正常了

**I confirm that I have read the ENTIRE supplied readme file and checked for relevant information on the repository wiki before raising this issue, and that if the solution to this issue is found in either location, it will be closed without further comment:**

 - [Yes ] .

**Comment by cerebrate** [comment]
Thanks for the catch! (I was expecting the upstream package to be robust against this sort of thing, but I guess not.)

I've added a fix for this to 2.3.
